
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 29 17:56:04 EST 2012
//----------------------------------------------------

package edu.wpi.termcount;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 2;
  public static final int BAR = 5;
  public static final int IN = 13;
  public static final int COLON = 6;
  public static final int SORTORPRED = 15;
  public static final int FORALL = 10;
  public static final int EOF = 0;
  public static final int VAR = 14;
  public static final int ARROW = 12;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int NOT = 4;
  public static final int EQUALS = 11;
  public static final int FORSOME = 9;
  public static final int LPAREN = 7;
  public static final int OR = 3;
}

